### ISSUE TITLE
Where do I put the Sitemap.configure block?

### ISSUE THREAD

**Issue by taimoorq** [viseztrance/rails-sitemap#17]
The instructions don't indicate where to put the Sitemap.configure block (to specify defaut file location of sitemap and other settings). The file generated during installation (/config/sitemap.rb) begins with Sitemap::Generator.instance.load...

Any help with where to put this would be appreciated.
Thanks

**Comment by viseztrance** [comment]
It's probably best to create a file, say for instance sitemap.rb in config/initializers and write your configure block there. It's loaded automatically so that's about it.

I don't know if the current code base will work in rails 4+, so that's something to be careful about.

**Comment by taimoorq** [comment]
Thanks for the reply. Using Rails 4.0.11 and adding that file in the config/initializers directory worked for me.

Thanks for the help!
